#!/bin/bash
set -euo pipefail

# Generates (and optionally installs) a sudoers drop-in for the backup LaunchAgent.
# Usage:
#   ./automation/setup_sudoers.sh            # preview only
#   ./automation/setup_sudoers.sh --apply    # validate with visudo and install (needs sudo)
# Optional env vars: BACKUP_SUDO_USER, STAGING_ROOT, SUDOERS_PATH

USER_NAME="${BACKUP_SUDO_USER:-$(id -un)}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STAGING_ROOT="${STAGING_ROOT:-${TMPDIR:-/tmp}/mac_backup_staging}"
SUDOERS_PATH="${SUDOERS_PATH:-/etc/sudoers.d/osx_backup_restore}"
ACTION="${1:-}"

escape_path() {
  # sudoers needs spaces escaped
  printf '%s' "$1" | sed 's/ /\\ /g'
}

repo_esc=$(escape_path "$REPO_ROOT")
staging_esc=$(escape_path "$STAGING_ROOT")

TMPFILE="$(mktemp)"
cat > "$TMPFILE" <<EOF
# mac_backup_restore automation sudoers (generated by setup_sudoers.sh)
Cmnd_Alias OSX_BACKUP_CMDS=/opt/homebrew/bin/rsync,/usr/bin/rsync,${repo_esc}/automation/daily_backup.sh,${repo_esc}/backup_mac.sh,/bin/chflags -R nouchg ${staging_esc}/System_Backup_*,/bin/chmod -R u+w ${staging_esc}/System_Backup_*,/bin/rm -rf ${staging_esc}/System_Backup_*
${USER_NAME} ALL=(root) NOPASSWD: OSX_BACKUP_CMDS
EOF

echo "Preview sudoers entry (user: $USER_NAME, staging: $STAGING_ROOT):"
cat "$TMPFILE"
echo

if [ "$ACTION" = "--apply" ]; then
  echo "Validating with visudo…"
  if sudo visudo -cf "$TMPFILE"; then
    echo "Installing to $SUDOERS_PATH..."
    sudo cp "$TMPFILE" "$SUDOERS_PATH"
    sudo chmod 440 "$SUDOERS_PATH"
    echo "Installed sudoers drop-in at $SUDOERS_PATH"
  else
    echo "visudo validation failed; not installing." >&2
    exit 1
  fi
else
  echo "Run with --apply to install (requires sudo)."
  echo "Example:"
  echo "  BACKUP_SUDO_USER=\"$USER_NAME\" STAGING_ROOT=\"$STAGING_ROOT\" SUDOERS_PATH=\"$SUDOERS_PATH\" $0 --apply"
fi
